spring.application.name=Spring-Data-JPA

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/JPA
spring.datasource.username=postgres
spring.datasource.password=chetan6462

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false